export const quotes = [
  "D'oh!",
  "Eat my shorts.",
  "Excellent.",
  "Ha-ha!",
  "Don't have a cow, man.",
  "Hi-dilly-ho, neighborino!",
  "Okily dokily!",
  "Mmm... donuts.",
  "Everything's coming up Milhouse!",
  "I am so smart! S-M-R-T!",
  "You don't win friends with salad.",
  "To alcohol! The cause of, and solution to, all of life's problems.",
  "Worst. Episode. Ever.",
  "My eyes! The goggles do nothing!",
  "I'm in danger.",
  "Me fail English? That's unpossible.",
  "Stupid sexy Flanders.",
  "Dental plan! Lisa needs braces.",
  "That's a paddlin'.",
  "In this house, we obey the laws of thermodynamics!",
  "I call the big one Bitey.",
  "It's a perfectly cromulent word.",
  "A noble spirit embiggens the smallest man.",
  "Oh, they have the internet on computers now?",
  "I used to be with ‘it’, but then they changed what ‘it’ was.",
  "Spider-Pig, Spider-Pig, does whatever a Spider-Pig does.",
  "I was saying 'Boo-urns'.",
  "Just because I don't care doesn't mean I don't understand.",
  "We must move forward, not backward. Upward, not forward. And always twirling, twirling, twirling towards freedom!",
  "Lousy Smarch weather.",
  "It tastes like... burning.",
  "Go banana!",
  "My cat's breath smells like cat food.",
  "Shoplifting is a victimless crime. Like punching someone in the dark.",
  "Let's all go out for some frosty chocolate milkshakes!",
  "I'm seeing double here! Four Krustys!",
  "It smells like Otto's jacket.",
  "Look, Marge, you don't know what it's like. I'm the one out there every day putting his life on the line. And I'm not out of order! You're out of order! The whole freakin' system is out of order! ",
  "Son, if you really want something in this life, you have to work for it. Now quiet! They're about to announce the lottery numbers.",
  "Facts are meaningless. You could use facts to prove anything that's even remotely true.",
  "Kids, you tried your best and you failed miserably. The lesson is, never try.",
  "I've sold monorails to Brockway, Ogdenville, and North Haverbrook, and by gum, it put them on the map!",
  "Is there a chance the track could bend?",
  "Not on your life, my Hindu friend!",
  "The ring came off my pudding can.",
  "Take my pen knife, my good man.",
  "I wish God were alive to see this.",
  "Operator! Give me the number for 911!",
  "Shut up, brain, or I'll stab you with a Q-tip!",
  "But Marge, what if we chose the wrong religion? Each week we just make God madder and madder.",
  "No beer and no TV make Homer something something.",
  "Go crazy?",
  "Don't mind if I do!",
  "Oh, loneliness and cheeseburgers are a dangerous mix.",
  "English side ruined, must use French side.",
  "There's nary an animal alive that can outrun a greased Scotsman.",
  "If I don't save the wee turtles, who will?",
  "Now my Woody Allen impression: 'I'm a neurotic nerd who likes to sleep with little girls'.",
  "It takes two to lie. One to lie and one to listen.",
  "Inflammable means flammable? What a country!",
  "Everybody loves a clown, so why don't you?",
  "I'm a people person. I work with people.",
  "Ahoy-hoy?",
  "Release the hounds.",
  "Smithers, who is that man?",
  "You'll have to speak up, I'm wearing a towel.",
  "What's the point of going out? We're just gonna wind up back here anyway.",
  "Bart, with $10,000, we'd be millionaires!",
  "I'm normally not a praying man, but if you're up there, please save me, Superman.",
  "A woman is a lot like a refrigerator. They're about six feet tall, 300 pounds. They make ice.",
  "I am the lizard queen!",
  "This is indeed a disturbing universe.",
  "So I says to Mabel, I says...",
  "It's my first day.",
  "I have a gut feeling Uter is here somewhere. After all, isn't there a little Uter in all of us?",
  "Am I so out of touch? No, it's the children who are wrong.",
  "Steamed hams.",
  "Aurora Borealis? At this time of year? At this time of day? In this part of the country? Localized entirely within your kitchen?",
  "Yes.",
  "May I see it?",
  "No.",
  "I'm not a state. I'm a monster.",
  "He thinks he's the pope of Chili-town.",
  "This is the worst day of my life.",
  "The worst day of your life so far.",
  "You'll live to see consumer-grade fusion.",
  "But Aquaman, you cannot marry a woman without gills. You're from two different worlds!",
  "Hi, I'm Troy McClure. You may remember me from such films as...",
  "Feels like I'm wearing nothing at all!",
  "TRAMAMPOLINE! TRAMBOPOLINE!",
  "Oh, I've had it with this school, Skinner! The low test scores, class after class of ugly, ugly children...",
  "Well, I'm from Utica and I've never heard anyone use the phrase 'steamed hams'.",
  "Oh, not in Utica, no. It's an Albany expression.",
  "I'm not a bad guy! I work hard, and I love my kids. So why should I have to spend half my Sunday hearing about how I'm going to Hell?",
  "Oh boy, sleep! That's where I'm a Viking!",
  "Lisa, in this house we obey the laws of THERMODYNAMICS!",
  "A booby trap that actually catches boobies.",
  "I've been called a greasy thug too. It never stops hurting. So here's what we're gonna do: we're gonna grease ourselves up real good and trash that place with a baseball bat.",
  "My Homer is not a Communist. He may be a liar, a pig, an idiot, a Communist, but he is NOT a porn star!",
  "Can't somebody else do it?"
];

export const getRandomQuote = (): string => {
  return quotes[Math.floor(Math.random() * quotes.length)];
};
